# Generated by Django 2.2.2 on 2019-06-13 11:07

import apps.news.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('language', apps.news.models.LanguagesField(choices=[(apps.news.models.LanguageChoice('Arabic'), 'Arabic'), (apps.news.models.LanguageChoice('French'), 'French'), (apps.news.models.LanguageChoice('Chinese'), 'Chinese'), (apps.news.models.LanguageChoice('Spanish'), 'Spanish')], default='fr', max_length=2)),
                ('background_url', models.URLField(default='https://images.pexels.com/photos/949587/pexels-photo-949587.jpeg')),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('language', apps.news.models.LanguagesField(choices=[(apps.news.models.LanguageChoice('Arabic'), 'Arabic'), (apps.news.models.LanguageChoice('French'), 'French'), (apps.news.models.LanguageChoice('Chinese'), 'Chinese'), (apps.news.models.LanguageChoice('Spanish'), 'Spanish')], default='fr', max_length=2)),
                ('logo_url', models.URLField(default='https://image.flaticon.com/icons/png/512/21/21601.png')),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', apps.news.models.LanguagesField(choices=[(apps.news.models.LanguageChoice('Arabic'), 'Arabic'), (apps.news.models.LanguageChoice('French'), 'French'), (apps.news.models.LanguageChoice('Chinese'), 'Chinese'), (apps.news.models.LanguageChoice('Spanish'), 'Spanish')], default='fr', max_length=2)),
                ('content', models.TextField()),
                ('minutes_read', models.IntegerField(default=5, max_length=15)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 6, 13, 11, 7, 42, 636069, tzinfo=utc))),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='news.Category')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='news.Source')),
            ],
        ),
    ]
