# Generated by Django 2.2.2 on 2019-06-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='minutes_read',
            field=models.IntegerField(default=0),
        ),
    ]
