# Generated by Django 2.2.2 on 2019-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190613_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
